import { describe, expect, it } from "vitest";
import { readSource } from "@/test/helpers/repoLiterals";

/**
 * PORTAL VIEW REACHABILITY — can a user actually GET to the page?
 *
 * The four portals are single pages that fake sub-routing internally: a `view`
 * state variable, a union type listing its legal values, an allow-list, a nav
 * array, and a render branch per value. Nothing keeps those five in step.
 *
 * `Driver App Preview` shipped unreachable THREE times: built only into Staff;
 * then moved within Staff while the written directions still pointed at its old
 * location; then imported into Management with no nav item, no route and no
 * render — an unused import whose own comment claimed the placement. An import
 * is not a placement. The standing rule is that a page is not complete until
 * its navigation placement is written down AND IMPLEMENTED, and implemented
 * means a user can reach it.
 *
 * This guard asserts both halves for every declared view: A RENDER BRANCH and
 * A WAY IN.
 *
 * THIS GUARD IS EXPECTED TO BE RED. It ships with one real finding. Green is
 * reached by wiring or deleting the view — never by allowlisting a finding.
 */

/**
 * ALLOWLIST — deep-link and drill-down views, each with a WRITTEN REASON.
 *
 * A reason must start with:
 *   DRILLDOWN — opened from a row click or another view, never from the
 *               sidebar. NAME what opens it.
 *   DEEPLINK  — reached only from a generated URL (an email, a notification).
 *               NAME what generates the link.
 *   FALLBACK  — rendered as a default/else branch, so no `view === 'x'` exists
 *               to find. CITE the file and line that renders it. This is the
 *               only prefix that may excuse a missing RENDER BRANCH, and only
 *               after reading the source.
 *
 * Seeded 2026-09-10 from the reachability sweep: every entry below was
 * classified LEGITIMATE. Nothing the sweep called ORPHANED is here.
 * This list may only SHRINK.
 */
type ViewAllowEntry = {
  readonly portal: string;
  readonly view: string;
  readonly reason: string;
};

const KNOWN_NO_NAV_ENTRIES: readonly ViewAllowEntry[] = [
  {
    portal: "staff",
    view: "operator-detail",
    reason: "DRILLDOWN opened from a driver row in Driver Hub (StaffPortal setCurrentView).",
  },
  {
    portal: "staff",
    view: "vehicle-detail",
    reason: "DRILLDOWN opened from a vehicle card in Vehicle Hub.",
  },
  {
    portal: "management",
    view: "operator-detail",
    reason: "DRILLDOWN opened from a driver row in Drivers.",
  },
  {
    portal: "management",
    view: "load-detail",
    reason: "DRILLDOWN opened from a load row in Loads.",
  },
  {
    portal: "management",
    view: "load-create",
    reason: "DRILLDOWN opened from the New Load action on Loads.",
  },
  {
    portal: "management",
    view: "load-edit",
    reason: "DRILLDOWN opened from the Edit action on a load.",
  },
  {
    portal: "management",
    view: "vehicle-detail",
    reason: "DRILLDOWN opened from a vehicle card in Vehicle Hub.",
  },
  {
    portal: "management",
    view: "email-catalog",
    reason: "DRILLDOWN opened from the Content Manager settings section.",
  },
  {
    portal: "operator",
    view: "ica-amendment",
    reason:
      "DEEPLINK /operator/ica-amendment?id=… generated by ICAAmendmentBuilderModal " +
      "and sent to the driver as a notification; no first-party nav item by design.",
  },
  {
    portal: "dispatch",
    view: "dispatch",
    reason:
      "FALLBACK rendered as the final else of the activePage ternary in " +
      "DispatchPortal.tsx:2593 (`: board`), so no `activePage === 'dispatch'` " +
      "comparison exists to find. Verified by reading the source 2026-09-10; it " +
      "has a nav item (path: 'dispatch', Driver Status). This is a limit of the " +
      "heuristic, not an unreachable page.",
  },
];

/** Ceiling. Falls freely; rises only for a new entry carrying its reason. */
const KNOWN_NO_NAV_MAX = 10;

interface PortalSpec {
  readonly portal: string;
  /** File holding the view union. */
  readonly unionFile: string;
  /** Captures the body of the union declaration. */
  readonly unionPattern: RegExp;
  /** Files searched for render branches and ways in. */
  readonly files: readonly string[];
  /** State variables compared against a view value in a render branch. */
  readonly stateVars: readonly string[];
  /** Functions that navigate to a view. */
  readonly setters: readonly string[];
  /** Object keys used by the nav arrays to carry a view value. */
  readonly navKeys: readonly string[];
}

const PORTALS: readonly PortalSpec[] = [
  {
    portal: "management",
    unionFile: "src/pages/management/ManagementPortal.tsx",
    unionPattern: /type ManagementView\s*=\s*([^;]+);/,
    files: ["src/pages/management/ManagementPortal.tsx"],
    stateVars: ["view"],
    setters: ["setView", "navigateToView"],
    navKeys: ["path", "view", "id"],
  },
  {
    portal: "staff",
    unionFile: "src/pages/staff/StaffPortal.tsx",
    unionPattern: /type StaffView\s*=\s*([^;]+);/,
    files: ["src/pages/staff/StaffPortal.tsx"],
    stateVars: ["currentView"],
    setters: ["setCurrentView"],
    navKeys: ["path", "view", "id"],
  },
  {
    portal: "dispatch",
    unionFile: "src/pages/dispatch/DispatchPortal.tsx",
    // Dispatch has no named union: the legal values are the inline type
    // argument on the `activePage` useState. Its path-routed screens
    // (/dispatch/loads and friends) are covered by the nav-target guard.
    unionPattern: /const \[activePage, setActivePage\] = useState<([^>]+)>/,
    files: ["src/pages/dispatch/DispatchPortal.tsx"],
    stateVars: ["activePage"],
    setters: ["setActivePage"],
    navKeys: ["path", "view", "id"],
  },
  {
    portal: "operator",
    unionFile: "src/lib/operatorRoutes.ts",
    unionPattern: /export type OperatorView\s*=\s*([^;]+);/,
    files: ["src/pages/operator/OperatorPortal.tsx", "src/lib/operatorRoutes.ts"],
    stateVars: ["view", "currentView"],
    setters: ["navigateToView", "setView"],
    navKeys: ["path", "view", "id"],
  },
];

function unionMembers(spec: PortalSpec): string[] {
  const src = readSource(spec.unionFile);
  const m = src.match(spec.unionPattern);
  if (!m) return [];
  return [...m[1].matchAll(/'([^']+)'/g)].map((x) => x[1]);
}

function corpus(spec: PortalSpec): string {
  return spec.files.map(readSource).join("\n");
}

function esc(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\-]/g, "\\$&");
}

function hasRenderBranch(text: string, spec: PortalSpec, view: string): boolean {
  const v = esc(view);
  if (new RegExp(`case\\s+'${v}'\\s*:`).test(text)) return true;
  return spec.stateVars.some((sv) =>
    new RegExp(`\\b${sv}\\s*===\\s*'${v}'`).test(text),
  );
}

function hasWayIn(text: string, spec: PortalSpec, view: string): boolean {
  const v = esc(view);
  if (spec.setters.some((fn) => new RegExp(`\\b${fn}\\(\\s*'${v}'`).test(text))) {
    return true;
  }
  return spec.navKeys.some((k) => new RegExp(`\\b${k}:\\s*'${v}'`).test(text));
}

/**
 * THE FAILURE MESSAGE IS THE PRODUCT. Names what was searched, which halves
 * came back empty, and the three exits — written for someone who did not build
 * the guard.
 */
function explain(
  spec: PortalSpec,
  view: string,
  render: boolean,
  wayIn: boolean,
): string {
  const missing = [!render && "NO RENDER BRANCH", !wayIn && "NO WAY IN"]
    .filter(Boolean)
    .join(" and ");
  return [
    ``,
    `${spec.portal} portal: view '${view}' is declared but ${missing}.`,
    ``,
    `Searched in ${spec.files.join(", ")}:`,
    `  render branch  ${spec.stateVars.map((s) => `${s} === '${view}'`).join("  ")}`,
    `                 case '${view}':                                  ${render ? "FOUND" : "(0)"}`,
    `  way in         ${spec.navKeys.map((k) => `${k}: '${view}'`).join("  ")}`,
    `                 ${spec.setters.map((s) => `${s}('${view}')`).join("  ")}   ${wayIn ? "FOUND" : "(0)"}`,
    ``,
    `To make this pass, do ONE of these:`,
    `  1. WIRE IT. A view needs BOTH halves: a nav item (or a setter call from`,
    `     the screen that opens it) AND a render branch. An entry in the type`,
    `     or in ALLOWED_VIEWS is neither — that is how 'Driver App Preview'`,
    `     shipped unreachable three times, the last as a bare import whose own`,
    `     comment claimed the placement.`,
    `  2. DELETE IT. Remove the value from the union and from ALLOWED_VIEWS. A`,
    `     view nobody can reach and nobody renders is dead weight that reads as`,
    `     done.`,
    `  3. ALLOWLIST IT, WITH A REASON — only if it is a drill-down or a deep`,
    `     link. Add to KNOWN_NO_NAV_ENTRIES in src/test/view-reachability.test.ts`,
    `     as { portal: '${spec.portal}', view: '${view}', reason: 'DRILLDOWN <what opens it>' }`,
    `     and raise KNOWN_NO_NAV_MAX by exactly one. Note this exit only covers`,
    `     a MISSING NAV ITEM. A missing render branch is never allowlistable —`,
    `     the page would show nothing.`,
  ].join("\n");
}

const allowed = new Set(KNOWN_NO_NAV_ENTRIES.map((e) => `${e.portal}::${e.view}`));

describe("portal view reachability — every declared view can be reached", () => {
  it("every allowlist entry carries a written reason", () => {
    const bad = KNOWN_NO_NAV_ENTRIES.filter(
      (e) => !/^(DRILLDOWN|DEEPLINK|FALLBACK) \S/.test(e.reason),
    );
    expect(
      bad.map((e) => `${e.portal}::${e.view}`),
      "Every KNOWN_NO_NAV_ENTRIES reason must start with 'DRILLDOWN ' (name what " +
        "opens it) or 'DEEPLINK ' (name what generates the link). A bare list of " +
        "names is a place to hide things.",
    ).toEqual([]);
  });

  it("the allowlist may only shrink", () => {
    expect(
      KNOWN_NO_NAV_ENTRIES.length,
      `KNOWN_NO_NAV_ENTRIES has ${KNOWN_NO_NAV_ENTRIES.length} entries but ` +
        `KNOWN_NO_NAV_MAX is ${KNOWN_NO_NAV_MAX}.`,
    ).toBeLessThanOrEqual(KNOWN_NO_NAV_MAX);
  });

  it("each portal's view union was actually found and parsed", () => {
    const empty = PORTALS.filter((p) => unionMembers(p).length === 0).map(
      (p) => `${p.portal} (${p.unionFile})`,
    );
    expect(
      empty,
      "A portal's view union could not be parsed, so this guard searched " +
        "nothing for it and would report green having checked nothing. Fix the " +
        "unionPattern in PORTALS — do not delete the portal from the list.",
    ).toEqual([]);
  });

  it("every declared view has a render branch and a way in", () => {
    const failures: string[] = [];
    const ids: string[] = [];

    for (const spec of PORTALS) {
      const text = corpus(spec);
      for (const view of unionMembers(spec)) {
        const render = hasRenderBranch(text, spec, view);
        const wayIn = hasWayIn(text, spec, view);
        if (render && wayIn) continue;
        if (allowed.has(`${spec.portal}::${view}`)) continue;
        ids.push(`${spec.portal}::${view}`);
        failures.push(explain(spec, view, render, wayIn));
      }
    }

    expect(
      ids,
      `${ids.length} declared view(s) cannot be reached or cannot render.\n` +
        `EXPECTED RED: this guard shipped on 2026-09-10 with 1 known finding ` +
        `(management 'app-errors'). Do not make it pass by allowlisting it.\n` +
        failures.join("\n" + "-".repeat(74) + "\n"),
    ).toEqual([]);
  });
});
