/**
 * The single registrar for the app-shell service worker.
 *
 * Registration is refused — and any matching stale registration unregistered —
 * in dev, inside an iframe, on Lovable preview hosts, and when ?sw=off is
 * present. Everything else about the worker (precache, navigation fallback,
 * route denylist) is generated by vite-plugin-pwa from vite.config.ts.
 */
const SW_URL = '/sw.js';

function inIframe(): boolean {
  try { return window.self !== window.top; } catch { return true; }
}

function isPreviewHost(host: string): boolean {
  return (
    host.startsWith('id-preview--')
    || host.startsWith('preview--')
    || host === 'lovableproject.com' || host.endsWith('.lovableproject.com')
    || host === 'lovableproject-dev.com' || host.endsWith('.lovableproject-dev.com')
    || host === 'beta.lovable.dev' || host.endsWith('.beta.lovable.dev')
  );
}

export function serviceWorkerAllowed(): boolean {
  if (!import.meta.env.PROD) return false;
  if (inIframe()) return false;
  if (isPreviewHost(window.location.hostname)) return false;
  if (new URLSearchParams(window.location.search).has('sw')
    && new URLSearchParams(window.location.search).get('sw') === 'off') return false;
  return true;
}

async function unregisterMatching(): Promise<void> {
  try {
    const regs = await navigator.serviceWorker?.getRegistrations();
    if (!regs) return;
    await Promise.all(regs.map(async (r) => {
      const url = r.active?.scriptURL ?? r.installing?.scriptURL ?? r.waiting?.scriptURL ?? '';
      if (!url || url.endsWith(SW_URL) || url.endsWith('/service-worker.js')) await r.unregister();
    }));
  } catch {
    /* nothing to clean up */
  }
}

export async function registerAppServiceWorker(): Promise<void> {
  if (!('serviceWorker' in navigator)) return;
  if (!serviceWorkerAllowed()) {
    await unregisterMatching();
    return;
  }
  try {
    await navigator.serviceWorker.register(SW_URL, { scope: '/' });
  } catch {
    /* offline support simply stays unavailable */
  }
}