REVOKE ALL ON FUNCTION public.assert_invoice_ready(uuid) FROM authenticated;
CREATE OR REPLACE FUNCTION public.create_invoice(p_load_id uuid, p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','extensions' AS $function$
DECLARE v_actor uuid:=public.current_profile_id();v_actor_name text:=public._audit_actor_name(public.current_profile_id());v_load public.loads%ROWTYPE;v_broker public.brokers%ROWTYPE;v_amount numeric:=coalesce((p_payload->>'amount')::numeric,0);v_sum numeric;v_path public.invoice_billing_path;v_claimed text:=nullif(p_payload->>'billing_path','');v_number text;v_id uuid;v_missing text;v_extra text;v_line jsonb;
BEGIN
IF NOT(public.has_role(auth.uid(),'management'::app_role) OR public.has_role(auth.uid(),'owner'::app_role) OR public.has_role(auth.uid(),'dispatcher'::app_role)) THEN RAISE EXCEPTION 'Only a dispatcher, management or owner may create an invoice.' USING ERRCODE='42501';END IF;
SELECT * INTO v_load FROM public.loads WHERE id=p_load_id FOR UPDATE;IF NOT FOUND OR v_load.company_id IS DISTINCT FROM public.current_company_id() THEN RAISE EXCEPTION 'Load not found.' USING ERRCODE='42501';END IF;
IF v_load.status<>'ready_to_invoice'::load_status THEN RAISE EXCEPTION 'Load % is %, not ready_to_invoice; it cannot be invoiced.',v_load.load_number,v_load.status USING ERRCODE='22000';END IF;
IF EXISTS(SELECT 1 FROM public.invoices WHERE load_id=p_load_id) THEN RAISE EXCEPTION 'Load % already has invoice %.',v_load.load_number,(SELECT invoice_number FROM public.invoices WHERE load_id=p_load_id) USING ERRCODE='23505';END IF;
SELECT coalesce(sum(amount),0) INTO v_sum FROM jsonb_to_recordset(coalesce(p_payload->'lines','[]'::jsonb)) AS t(line_type text,amount numeric);IF round(v_sum,2)<>round(v_amount,2) THEN RAISE EXCEPTION 'Invoice lines sum to % but the payload states %.',round(v_sum,2),round(v_amount,2) USING ERRCODE='22000';END IF;
SELECT string_agg(c.charge_type||' '||c.amount::text,', ') INTO v_missing FROM public.load_charges c WHERE c.load_id=p_load_id AND NOT EXISTS(SELECT 1 FROM jsonb_to_recordset(coalesce(p_payload->'lines','[]'::jsonb)) AS l(load_charge_id uuid) WHERE l.load_charge_id=c.id);IF v_missing IS NOT NULL THEN RAISE EXCEPTION 'Invoice for % omits charge(s) the load carries: %.',v_load.load_number,v_missing USING ERRCODE='22000';END IF;
SELECT string_agg(coalesce(l.load_charge_id::text,'(null)'),', ') INTO v_extra FROM jsonb_to_recordset(coalesce(p_payload->'lines','[]'::jsonb)) AS l(line_type text,load_charge_id uuid) WHERE l.line_type='charge' AND(l.load_charge_id IS NULL OR NOT EXISTS(SELECT 1 FROM public.load_charges c WHERE c.id=l.load_charge_id AND c.load_id=p_load_id));IF v_extra IS NOT NULL THEN RAISE EXCEPTION 'Invoice for % bills charge(s) the load does not carry: %.',v_load.load_number,v_extra USING ERRCODE='22000';END IF;
IF v_load.broker_id IS NOT NULL THEN SELECT * INTO v_broker FROM public.brokers WHERE id=v_load.broker_id;IF NOT FOUND OR v_broker.company_id IS DISTINCT FROM public.current_company_id() THEN RAISE EXCEPTION 'Load not found.' USING ERRCODE='42501';END IF;END IF;
v_path:=CASE WHEN v_broker.id IS NOT NULL AND v_broker.factoring_status='approved'::broker_factoring_status THEN 'factored'::invoice_billing_path ELSE 'direct'::invoice_billing_path END;IF v_claimed IS NOT NULL AND v_claimed<>v_path::text THEN RAISE EXCEPTION 'Payload asks to bill % but broker factoring status % forces %.',v_claimed,coalesce(v_broker.factoring_status::text,'no broker'),v_path USING ERRCODE='22000';END IF;
PERFORM public.assert_invoice_ready(p_load_id);v_number:=public.allocate_invoice_number();
INSERT INTO public.invoices(load_id,broker_id,broker_name_snapshot,broker_billing_email_snapshot,invoice_number,billing_path,amount,status,created_by,updated_by) VALUES(p_load_id,v_load.broker_id,v_broker.company_name,v_broker.billing_email,v_number,v_path,round(v_amount,2),'open'::invoice_status,v_actor,v_actor) RETURNING id INTO v_id;
FOR v_line IN SELECT * FROM jsonb_array_elements(coalesce(p_payload->'lines','[]'::jsonb)) LOOP INSERT INTO public.invoice_line_items(invoice_id,line_type,description,amount,load_charge_id,charge_type,created_by) VALUES(v_id,v_line->>'line_type',nullif(v_line->>'description',''),round(coalesce((v_line->>'amount')::numeric,0),2),nullif(v_line->>'load_charge_id','')::uuid,nullif(v_line->>'charge_type',''),v_actor);END LOOP;
PERFORM set_config('superdrive.invoice_issue','on',true);PERFORM public.update_load_status(p_load_id,'invoiced'::load_status,NULL);PERFORM set_config('superdrive.invoice_issue','',true);
INSERT INTO public.audit_log(actor_id,actor_name,action,entity_type,entity_id,entity_label,metadata) VALUES(v_actor,v_actor_name,'invoice_created','invoices',v_id,v_number,jsonb_build_object('load_id',p_load_id,'load_number',v_load.load_number,'amount',round(v_amount,2),'billing_path',v_path,'broker_factoring_status',coalesce(v_broker.factoring_status::text,'no broker'),'line_count',jsonb_array_length(coalesce(p_payload->'lines','[]'::jsonb))));RETURN jsonb_build_object('invoice_id',v_id,'invoice_number',v_number,'billing_path',v_path,'amount',round(v_amount,2),'load_number',v_load.load_number);
END;$function$;
REVOKE ALL ON FUNCTION public.create_invoice(uuid,jsonb) FROM PUBLIC,anon;GRANT EXECUTE ON FUNCTION public.create_invoice(uuid,jsonb) TO authenticated,service_role;