import type { Database } from '@/integrations/supabase/types';

export type AppRole = Database['public']['Enums']['app_role'];

export type HelpSurface = 'management' | 'driver-pwa';

export interface HelpEntry {
  id: string;
  title: string;
  page: string;
  surface: HelpSurface;
  route: string;
  /** Short text shown in typeahead results, e.g. "Operations → Onboard Systems" */
  breadcrumb: string;
  keywords: string[];
  audience: AppRole[];
  /** Optional numbered steps for simple actions. */
  steps?: string[];
  /** FAQ article ids that relate to this entry (for cross-linking). */
  relatedFaqIds?: string[];
  /** True if the link should open in a new tab because it is a driver-facing path. */
  external?: boolean;
}

// Audience aliases used by the index.
const ALL_STAFF: AppRole[] = ['owner', 'management', 'onboarding_staff', 'dispatcher'];
const MANAGEMENT: AppRole[] = ['owner', 'management'];
const DISPATCH_OPS: AppRole[] = ['owner', 'management', 'dispatcher'];
const ONBOARDING: AppRole[] = ['owner', 'management', 'onboarding_staff'];

export const STAFF_HELP_INDEX: HelpEntry[] = [
  // Dashboard group
  {
    id: 'overview',
    title: 'Management Overview',
    page: 'Dashboard',
    surface: 'management',
    route: '/dashboard?view=overview',
    breadcrumb: 'Dashboard',
    keywords: ['overview', 'dashboard', 'kpis', 'compliance summary', 'home', 'main page', 'metrics', 'truck down', 'alerts', 'installs'],
    audience: ALL_STAFF,
    steps: ['Open Dashboard from the sidebar.', 'Review the KPI cards and compliance summary.', 'Click any alert to jump to the relevant section.'],
  },
  {
    id: 'applications',
    title: 'Application Review',
    page: 'Applications',
    surface: 'management',
    route: '/dashboard?view=applications',
    breadcrumb: 'Dashboard',
    keywords: ['application review', 'applications', 'applicant', 'review status', 'approve', 'deny', 'revisions', 'propose changes', 'revert', 'submitted application', 'signature'],
    audience: ALL_STAFF,
    steps: ['Go to Applications.', 'Select a status filter (Pending, Approved, etc.).', 'Click an applicant to open the review drawer.', 'Use Propose Changes or Revert as needed.'],
  },
  {
    id: 'pipeline',
    title: 'Onboarding Pipeline',
    page: 'Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Dashboard',
    keywords: ['pipeline', 'onboarding', 'applicant pipeline', 'stages', 'drivers', 'applicants', 'status', 'stage 1', 'stage 2', 'stage 9', 'go live', 'coordinator', 'idle'],
    audience: ALL_STAFF,
    steps: ['Go to Onboarding Pipeline.', 'Use filters or search to find the applicant.', 'Click a row to open the driver detail panel.'],
  },
  {
    id: 'stage-1-background',
    title: 'Stage 1 — Background Check',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Pipeline → Stage 1',
    keywords: ['stage 1', 'background check', 'mvr', 'ch', 'criminal history', 'motor vehicle record', 'background verification', 'approved'],
    audience: ALL_STAFF,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 1 — Background Check.', 'Review MVR and Criminal History status.', 'Approve when both are cleared.'],
  },
  {
    id: 'stage-2-documents',
    title: 'Stage 2 — Application Review',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Pipeline → Stage 2',
    keywords: ['stage 2', 'application review', 'documents', 'submitted application', 'propose changes', 'revert', 'review notes', 'corrections'],
    audience: ALL_STAFF,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 2 — Application Review.', 'View the submitted application snapshot.', 'Use Propose Changes or Revert.'],
  },
  {
    id: 'stage-3-ica',
    title: 'Stage 3 — ICA Contract',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Pipeline → Stage 3',
    keywords: ['stage 3', 'ica', 'contract', 'independent contractor agreement', 'signature', 'carrier signature', 'send ica'],
    audience: ALL_STAFF,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 3 — ICA.', 'Click Send ICA or review the signed contract.', 'For amendments, use ICA Amendments.'],
  },
  {
    id: 'stage-4-mo-registration',
    title: 'Stage 4 — MO Registration',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Pipeline → Stage 4',
    keywords: ['stage 4', 'mo registration', 'missouri registration', 'truck title', 'registration', '2290', 'cab card'],
    audience: ALL_STAFF,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 4 — MO Registration.', 'Confirm the truck title and registration are received.'],
  },
  {
    id: 'stage-5-equipment',
    title: 'Stage 5 — Onboard Systems',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Pipeline → Stage 5',
    keywords: ['stage 5', 'onboard systems', 'equipment', 'decal', 'eld', 'fuel card', 'truck photos', 'dash cam', 'onboard systems assignment sheet', 'osas', 'verified by staff', 'bestpass'],
    audience: ALL_STAFF,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 5 — Onboard Systems.', 'Verify equipment assignment on the Onboard Systems Assignment Sheet (OSAS).', 'Confirm truck photos and decal are uploaded.'],
  },
  {
    id: 'stage-6-pe-screening',
    title: 'Stage 6 — PE Screening',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Pipeline → Stage 6',
    keywords: ['stage 6', 'pe screening', 'pre employment', 'previous employer', 'pei', 'gfe', 'good faith effort', 'drug test', 'test result'],
    audience: ONBOARDING,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 6 — PE Screening.', 'Add previous employers and send PEI requests.', 'Review the auto-cadence and Good Faith Effort record.'],
  },
  {
    id: 'stage-7-insurance',
    title: 'Stage 7 — Insurance',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Pipeline → Stage 7',
    keywords: ['stage 7', 'insurance', 'email insurance', 'insurance company', 'cargo insurance', 'added date'],
    audience: ONBOARDING,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 7 — Insurance.', 'Click Email Insurance Company to notify the provider.', 'Enter the insurance added date when confirmed.'],
  },
  {
    id: 'stage-9-payroll',
    title: 'Stage 9 — Payroll and Procedures',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Pipeline → Stage 9',
    keywords: ['stage 9', 'payroll', 'pay setup', 'bol procedures', 'handbook', 'load out', 'procedures', 'payroll calendar', 'contractor pay setup'],
    audience: ONBOARDING,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 9 — Payroll and Procedures.', 'Confirm BOL Procedures, Handbook, and Load Out are acknowledged.', 'Driver signs the Pay Setup agreement.'],
  },
  {
    id: 'pei-queue',
    title: 'PEI Queue',
    page: 'PEI Queue',
    surface: 'management',
    route: '/dashboard?view=pei-queue',
    breadcrumb: 'Dashboard',
    keywords: ['pei queue', 'previous employer inquiry', 'pre employment', 'verification', 'follow up', 'gfe', 'queue', 'pending pei'],
    audience: ONBOARDING,
    steps: ['Go to PEI Queue.', 'Review pending verifications and auto-follow-up status.', 'Click a driver to see their PEI history.'],
  },
  {
    id: 'messages',
    title: 'Messages',
    page: 'Messages',
    surface: 'management',
    route: '/dashboard?view=messages',
    breadcrumb: 'Dashboard',
    keywords: ['messages', 'inbox', 'sms', 'text', 'chat', 'bulk message', 'notify driver', 'messaging'],
    audience: ALL_STAFF,
    steps: ['Go to Messages.', 'Select a driver to open the thread.', 'Type and send, or use Bulk Message to message multiple drivers.'],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    page: 'Notifications',
    surface: 'management',
    route: '/dashboard?view=notifications',
    breadcrumb: 'Dashboard',
    keywords: ['notifications', 'alerts', 'bell', 'mentions', 'assigned', 'notification history', 'mark read', 'triage'],
    audience: ALL_STAFF,
    steps: ['Go to Notifications.', 'Use Action, All, or Mentions tabs.', 'Assign or dismiss notifications as needed.'],
  },

  // Operations group
  {
    id: 'fleet-compliance',
    title: 'Fleet Compliance',
    page: 'Fleet Compliance',
    surface: 'management',
    route: '/dashboard?view=compliance',
    breadcrumb: 'Operations',
    keywords: ['compliance', 'fleet compliance', 'cdl', 'med cert', 'medical certificate', 'irp', 'expiring', 'expired', 'critical', 'warning', 'alerts', 'renew'],
    audience: ALL_STAFF,
    steps: ['Go to Fleet Compliance.', 'Switch between Cards and List views.', 'Click an alert to open the driver record.'],
  },
  {
    id: 'dispatch-board',
    title: 'Dispatch Board',
    page: 'Dispatch Board',
    surface: 'management',
    route: '/dashboard?view=dispatch',
    breadcrumb: 'Operations',
    keywords: ['dispatch', 'dispatch board', 'dispatched', 'not dispatched', 'home', 'truck down', 'status', 'decals', 'binder', 'history', 'driver history'],
    audience: DISPATCH_OPS,
    steps: ['Go to Dispatch Board.', 'Filter by status (Dispatched, Not Dispatched, Home, Truck Down).', 'Click Binder or Decals on a driver card to open details.'],
  },
  {
    id: 'dispatch-decal-photos',
    title: 'View Decal Photos from Dispatch',
    page: 'Dispatch Board',
    surface: 'management',
    route: '/dashboard?view=dispatch',
    breadcrumb: 'Operations → Dispatch',
    keywords: ['decals', 'decal photos', 'dispatch', 'view photos', 'stage 5 photos', 'truck decal'],
    audience: DISPATCH_OPS,
    steps: ['Go to Dispatch Board.', 'Find the driver row.', 'Click the camera/Decals icon to open the photo viewer.', 'Use arrows to navigate between photos.'],
  },
  {
    id: 'dispatch-binder',
    title: 'Open Inspection Binder from Dispatch',
    page: 'Dispatch Board',
    surface: 'management',
    route: '/dashboard?view=dispatch',
    breadcrumb: 'Operations → Dispatch',
    keywords: ['binder', 'inspection binder', 'dispatch', 'open binder', 'flipbook', 'cover page'],
    audience: DISPATCH_OPS,
    steps: ['Go to Dispatch Board.', 'Find the driver row.', 'Click the Binder button to jump to the driver’s flipbook cover page.'],
  },
  {
    id: 'dispatch-history',
    title: 'Download Driver Dispatch History',
    page: 'Dispatch Board',
    surface: 'management',
    route: '/dashboard?view=dispatch',
    breadcrumb: 'Operations → Dispatch',
    keywords: ['driver history', 'dispatch history', 'download', 'pdf', 'png', 'date range', 'history'],
    audience: DISPATCH_OPS,
    steps: ['Go to Dispatch Board.', 'Click the driver’s history/download icon.', 'Select a date range and choose PDF or PNG.'],
  },
  {
    id: 'driver-hub',
    title: 'Driver Hub',
    page: 'Driver Hub',
    surface: 'management',
    route: '/dashboard?view=drivers',
    breadcrumb: 'Operations',
    keywords: ['driver hub', 'drivers', 'driver roster', 'fleet roster', 'driver profile', 'driver docs', 'vault', 'documents', 'deactivate', 'terminate'],
    audience: ALL_STAFF,
    steps: ['Go to Driver Hub.', 'Search or select a driver.', 'Use the tabs to view profile, documents, compliance, and stages.'],
  },
  {
    id: 'driver-hub-binder',
    title: 'Open a Driver’s Inspection Binder',
    page: 'Driver Hub',
    surface: 'management',
    route: '/dashboard?view=drivers',
    breadcrumb: 'Operations → Driver Hub',
    keywords: ['open binder', 'driver binder', 'inspection binder', 'driver docs', 'dot binder'],
    audience: ALL_STAFF,
    steps: ['Go to Driver Hub.', 'Select the driver.', 'Click Open in Binder / DOT Inspection Binder.'],
  },
  {
    id: 'deactivate-driver',
    title: 'Deactivate a Driver',
    page: 'Driver Hub',
    surface: 'management',
    route: '/dashboard?view=drivers',
    breadcrumb: 'Operations → Driver Hub',
    keywords: ['deactivate', 'terminate', 'driver leaving', 'not compliant', 'truck down', 'personal reasons', 'safety advisor', 'notify tracy', 'tracy mcquilken'],
    audience: MANAGEMENT,
    steps: ['Go to Driver Hub and select the driver.', 'Scroll to the Deactivate section.', 'Select a reason and add notes.', 'Click Deactivate, then notify the Safety Advisor.'],
  },
  {
    id: 'vehicle-hub',
    title: 'Vehicle Hub',
    page: 'Vehicle Hub',
    surface: 'management',
    route: '/dashboard?view=vehicle-hub',
    breadcrumb: 'Operations',
    keywords: ['vehicle hub', 'trucks', 'fleet', 'equipment', 'registration', '2290', 'truck photos', 'decal photos', 'maintenance', 'repairs'],
    audience: ALL_STAFF,
    steps: ['Go to Vehicle Hub.', 'Switch between Cards and Table views.', 'Click a truck to view details, maintenance, and photos.'],
  },
  {
    id: 'vehicle-hub-truck-photos',
    title: 'View Truck Photos in Vehicle Hub',
    page: 'Vehicle Hub',
    surface: 'management',
    route: '/dashboard?view=vehicle-hub',
    breadcrumb: 'Operations → Vehicle Hub',
    keywords: ['truck photos', 'vehicle photos', 'flipbook', 'album', 'view truck', 'front', 'rear', 'driver side'],
    audience: ALL_STAFF,
    steps: ['Go to Vehicle Hub.', 'Select the truck.', 'Click Truck Photos to open the flipbook viewer.', 'Use arrows to navigate.'],
  },
  {
    id: 'vehicle-hub-decal-photos',
    title: 'View Decal Photos in Vehicle Hub',
    page: 'Vehicle Hub',
    surface: 'management',
    route: '/dashboard?view=vehicle-hub',
    breadcrumb: 'Operations → Vehicle Hub',
    keywords: ['decal photos', 'decal', 'vehicle hub', 'decal icon', 'badge'],
    audience: ALL_STAFF,
    steps: ['Go to Vehicle Hub.', 'Select the truck.', 'Click Decal Photos to view the decal set.'],
  },
  {
    id: 'vehicle-hub-maintenance',
    title: 'Repairs and Maintenance',
    page: 'Vehicle Hub',
    surface: 'management',
    route: '/dashboard?view=vehicle-hub',
    breadcrumb: 'Operations → Vehicle Hub',
    keywords: ['maintenance', 'repairs', 'invoice', 'receipt', 'eyeball', 'view invoice', 'ai invoice scanner', 'records'],
    audience: ALL_STAFF,
    steps: ['Go to Vehicle Hub and select the truck.', 'Open the Repairs and Maintenance section.', 'Click View Invoice to see the uploaded receipt.'],
  },
  {
    id: 'inspection-binder',
    title: 'DOT Inspection Binder',
    page: 'DOT Inspection Binder',
    surface: 'management',
    route: '/dashboard?view=inspection-binder',
    breadcrumb: 'Operations',
    keywords: ['inspection binder', 'dot binder', 'admin binder', 'select driver', 'flipbook', 'pages', 'cover'],
    audience: ALL_STAFF,
    steps: ['Go to DOT Inspection Binder.', 'Select a driver from the searchable dropdown.', 'View the flipbook or individual pages.'],
  },
  {
    id: 'document-hub',
    title: 'Document Hub',
    page: 'Document Hub',
    surface: 'management',
    route: '/dashboard?view=docs-hub',
    breadcrumb: 'Operations',
    keywords: ['document hub', 'documents', 'library', 'pdf', 'company documents', 'driver documents', 'document manager'],
    audience: ALL_STAFF,
    steps: ['Go to Document Hub.', 'Browse folders or use the search bar.', 'Click a document to view, edit, or manage versions.'],
  },
  {
    id: 'onboard-systems',
    title: 'Onboard Systems',
    page: 'Onboard Systems',
    surface: 'management',
    route: '/dashboard?view=equipment',
    breadcrumb: 'Operations',
    keywords: ['onboard systems', 'equipment inventory', 'equipment', 'eld', 'bestpass', 'fuel card', 'dash cam', 'assign', 'return', 'deactivate', 'unassigned inventory'],
    audience: ALL_STAFF,
    steps: ['Go to Onboard Systems.', 'Select a device category (ELD, Dash Camera, BestPass, Fuel Card).', 'Assign, return, or deactivate items.'],
  },
  {
    id: 'fuel-cards',
    title: 'Fuel Cards',
    page: 'Onboard Systems',
    surface: 'management',
    route: '/dashboard?view=equipment&section=fuel_card',
    breadcrumb: 'Operations → Onboard Systems',
    keywords: ['fuel card', 'wex', 'deactivate', 'deactivated', 'available', 'unassigned', 'assign fuel card', 'return'],
    audience: ALL_STAFF,
    steps: ['Go to Onboard Systems.', 'Scroll to Fuel Cards.', 'Assign a card, or move a card to Deactivated.'],
  },
  {
    id: 'elds',
    title: 'ELDs',
    page: 'Onboard Systems',
    surface: 'management',
    route: '/dashboard?view=equipment&section=eld',
    breadcrumb: 'Operations → Onboard Systems',
    keywords: ['eld', 'electronic logging device', 'device', 'assign eld', 'available', 'unassigned'],
    audience: ALL_STAFF,
    steps: ['Go to Onboard Systems.', 'Scroll to ELDs.', 'Assign or return ELD units.'],
  },
  {
    id: 'bestpass',
    title: 'BestPass',
    page: 'Onboard Systems',
    surface: 'management',
    route: '/dashboard?view=equipment&section=bestpass',
    breadcrumb: 'Operations → Onboard Systems',
    keywords: ['bestpass', 'toll', 'transponder', 'assign bestpass', 'available'],
    audience: ALL_STAFF,
    steps: ['Go to Onboard Systems.', 'Scroll to BestPass.', 'Assign or return transponders.'],
  },
  {
    id: 'dash-cams',
    title: 'Dash Cameras',
    page: 'Onboard Systems',
    surface: 'management',
    route: '/dashboard?view=equipment&section=dash_cam',
    breadcrumb: 'Operations → Onboard Systems',
    keywords: ['dash cam', 'dash camera', 'camera', 'dashcam', 'assign dash camera', 'available'],
    audience: ALL_STAFF,
    steps: ['Go to Onboard Systems.', 'Scroll to Dash Cameras.', 'Assign or return cameras.'],
  },
  {
    id: 'mo-plate-registry',
    title: 'MO Plate Registry',
    page: 'MO Plate Registry',
    surface: 'management',
    route: '/dashboard?view=mo-plates',
    breadcrumb: 'Operations',
    keywords: ['mo plate', 'missouri plate', 'plate registry', 'irp', 'registration', 'cab card', 'expiration', 'assign plate'],
    audience: ALL_STAFF,
    steps: ['Go to MO Plate Registry.', 'Add or edit plates and link them to drivers.', 'Expiration dates sync with the driver’s IRP documents.'],
  },
  {
    id: 'equipment-return',
    title: 'Equipment Return Instructions',
    page: 'Onboard Systems',
    surface: 'management',
    route: '/dashboard?view=equipment',
    breadcrumb: 'Operations → Onboard Systems',
    keywords: ['equipment return', 'mailing instructions', 'ups store', 'po box', 'receipt', 'deactivated', 'return equipment'],
    audience: ALL_STAFF,
    steps: ['When a driver is deactivated, go to Onboard Systems.', 'Find the driver’s assignments.', 'Send mailing instructions and wait for the shipping receipt upload.'],
  },

  // Admin group
  {
    id: 'resource-center',
    title: 'Resource Center',
    page: 'Resource Center',
    surface: 'management',
    route: '/dashboard?view=resource-center',
    breadcrumb: 'Admin',
    keywords: ['resource center', 'company documents', 'service library', 'library', 'documents', 'driver resources', 'forms'],
    audience: ALL_STAFF,
    steps: ['Go to Resource Center.', 'Browse categories or search for a resource.', 'Add or edit resources for drivers.'],
  },
  {
    id: 'staff-directory',
    title: 'Staff Directory',
    page: 'Staff Directory',
    surface: 'management',
    route: '/dashboard?view=staff',
    breadcrumb: 'Admin',
    keywords: ['staff directory', 'staff', 'users', 'roles', 'invite staff', 'add user', 'management', 'permissions'],
    audience: MANAGEMENT,
    steps: ['Go to Staff Directory.', 'Invite a new staff member or edit existing roles.', 'Assign the correct role (owner, management, onboarding, dispatcher).'],
  },
  {
    id: 'faq-manager',
    title: 'FAQ Manager',
    page: 'FAQ Manager',
    surface: 'management',
    route: '/dashboard?view=faq',
    breadcrumb: 'Admin',
    keywords: ['faq manager', 'faqs', 'knowledge base', 'articles', 'staff help', 'owner operator faq', 'help articles', 'add faq'],
    audience: MANAGEMENT,
    steps: ['Go to FAQ Manager.', 'Create a new FAQ and choose the audience (owner-operators or staff).', 'Publish so it appears in Staff Help sources.'],
  },
  {
    id: 'staff-help',
    title: 'Staff Help',
    page: 'Staff Help',
    surface: 'management',
    route: '/dashboard?view=staff-help',
    breadcrumb: 'Admin',
    keywords: ['staff help', 'help', 'assistant', 'ai', 'search', 'support', 'how to', 'instructions'],
    audience: ALL_STAFF,
    steps: ['Go to Staff Help.', 'Type a keyword or ask a question.', 'Click a source or Go button to navigate to the page.'],
  },
  {
    id: 'pipeline-config',
    title: 'Pipeline Config',
    page: 'Pipeline Config',
    surface: 'management',
    route: '/dashboard?view=pipeline-config',
    breadcrumb: 'Admin',
    keywords: ['pipeline config', 'stages', 'stage names', 'stage order', 'completion', 'configure pipeline', 'onboarding stages'],
    audience: MANAGEMENT,
    steps: ['Go to Pipeline Config.', 'Edit stage names, completion criteria, or visibility.', 'Save changes to update the onboarding pipeline.'],
  },
  {
    id: 'activity-log',
    title: 'Activity Log',
    page: 'Activity Log',
    surface: 'management',
    route: '/dashboard?view=activity',
    breadcrumb: 'Admin',
    keywords: ['activity log', 'audit log', 'history', 'actions', 'filters', 'who did what', 'staff actions'],
    audience: MANAGEMENT,
    steps: ['Go to Activity Log.', 'Use filters for action, date, staff, or applicant.', 'Click an entry to see details.'],
  },
  {
    id: 'content-manager',
    title: 'Content Manager',
    page: 'Content Manager',
    surface: 'management',
    route: '/dashboard?view=content-manager',
    breadcrumb: 'Admin',
    keywords: ['content manager', 'email templates', 'templates', 'birthday', 'anniversary', 'cards', 'email content'],
    audience: MANAGEMENT,
    steps: ['Go to Content Manager.', 'Select an email template or card.', 'Edit and save the content.'],
  },
  {
    id: 'forms-catalog',
    title: 'Forms Catalog',
    page: 'Forms Catalog',
    surface: 'management',
    route: '/dashboard?view=forms-catalog',
    breadcrumb: 'Admin',
    keywords: ['forms catalog', 'forms', 'fillable forms', 'documents', 'passenger authorization', 'company forms'],
    audience: MANAGEMENT,
    steps: ['Go to Forms Catalog.', 'Browse available forms.', 'Open a form to fill, sign, or assign to a driver.'],
  },
  {
    id: 'whats-new',
    title: "What's New",
    page: "What's New",
    surface: 'management',
    route: '/dashboard?view=whats-new',
    breadcrumb: 'Admin',
    keywords: ['whats new', 'release notes', 'updates', 'changelog', 'new features'],
    audience: ALL_STAFF,
    steps: ['Go to What\'s New.', 'Read recent release notes and updates.'],
  },
  {
    id: 'broadcast-email',
    title: 'Broadcast Email',
    page: 'Broadcast Email',
    surface: 'management',
    route: '/dashboard?view=broadcast',
    breadcrumb: 'Admin',
    keywords: ['broadcast email', 'mass email', 'all drivers', 'announcement', 'email all'],
    audience: MANAGEMENT,
    steps: ['Go to Broadcast Email.', 'Compose the message.', 'Select recipients and send.'],
  },
  {
    id: 'email-log',
    title: 'Email Log',
    page: 'Email Log',
    surface: 'management',
    route: '/dashboard?view=email-log',
    breadcrumb: 'Admin',
    keywords: ['email log', 'sent emails', 'email history', 'delivery status', 'failed email'],
    audience: MANAGEMENT,
    steps: ['Go to Email Log.', 'Search by recipient or subject.', 'Review delivery status and errors.'],
  },
  {
    id: 'carrier-signature',
    title: 'Carrier Signature Settings',
    page: 'Carrier Signature',
    surface: 'management',
    route: '/dashboard?view=carrier-signature',
    breadcrumb: 'Admin',
    keywords: ['carrier signature', 'ica signature', 'carrier sign', 'signature settings', 'sign ica'],
    audience: MANAGEMENT,
    steps: ['Go to Carrier Signature Settings.', 'Upload or update the carrier signature used on ICA documents.', 'Save changes.'],
  },
  {
    id: 'lease-terminations',
    title: 'Lease Terminations',
    page: 'Lease Terminations',
    surface: 'management',
    route: '/dashboard?view=terminations',
    breadcrumb: 'Admin',
    keywords: ['lease terminations', 'terminations', 'ica termination', 'end lease', 'remove driver'],
    audience: MANAGEMENT,
    steps: ['Go to Lease Terminations.', 'Create or review termination records.', 'Link to the related ICA contract.'],
  },
  {
    id: 'ica-amendments',
    title: 'ICA Amendments',
    page: 'ICA Amendments',
    surface: 'management',
    route: '/dashboard?view=terminations',
    breadcrumb: 'Admin',
    keywords: ['ica amendment', 'amend', 'add unit', 'remove unit', 'replace unit', 'additional unit', 'lease amendment'],
    audience: MANAGEMENT,
    steps: ['Open the driver in the Onboarding Pipeline.', 'Use ICA Amendments for Add Unit or Remove & Replace.', 'Have the operator sign the amendment.'],
  },
  {
    id: 'notification-preferences',
    title: 'Notification Preferences',
    page: 'Notifications',
    surface: 'management',
    route: '/dashboard?view=notifications',
    breadcrumb: 'Admin',
    keywords: ['notification preferences', 'email preferences', 'sms preferences', 'alert settings', 'notification settings'],
    audience: ALL_STAFF,
    steps: ['Open the notification preferences from the bell or account menu.', 'Toggle email/SMS alerts by category.', 'Save changes.'],
  },

  // Driver PWA (informational entries for staff helping drivers)
  {
    id: 'driver-home',
    title: 'Driver Home Page',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/home',
    breadcrumb: 'Driver PWA',
    keywords: ['driver home', 'pwa home', 'driver app', 'front facing app', 'operator home', 'home tab'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers see the Home tab after they are fully onboarded.', 'It shows the next dispatch, compliance status, and quick actions.'],
  },
  {
    id: 'driver-progress',
    title: 'Driver Onboarding Progress',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/status',
    breadcrumb: 'Driver PWA',
    keywords: ['driver progress', 'my progress', 'onboarding status', 'status tab', 'stages', 'checklist'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Status/Progress tab to see onboarding stages.', 'Staff can guide them to upload documents or sign forms here.'],
  },
  {
    id: 'driver-documents',
    title: 'Driver Documents Upload',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/documents',
    breadcrumb: 'Driver PWA',
    keywords: ['driver documents', 'upload documents', 'documents tab', 'front facing upload', 'photos', 'files'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Documents tab.', 'They select the required document type and upload a photo or file.', 'Staff review the upload in Driver Hub or Pipeline.'],
  },
  {
    id: 'driver-doc-hub',
    title: 'Driver Doc Hub',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/doc-hub',
    breadcrumb: 'Driver PWA',
    keywords: ['driver doc hub', 'doc hub', 'required documents', 'acknowledge', 'sign'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Doc Hub.', 'They view and acknowledge required documents.', 'Unsigned documents are flagged here.'],
  },
  {
    id: 'driver-binder',
    title: 'Driver Inspection Binder',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/binder',
    breadcrumb: 'Driver PWA',
    keywords: ['driver binder', 'inspection binder', 'dot binder', 'driver app binder'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Inspection Binder tab.', 'They can view the flipbook or individual pages.'],
  },
  {
    id: 'driver-my-truck',
    title: 'Driver My Truck',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/my-truck',
    breadcrumb: 'Driver PWA',
    keywords: ['my truck', 'truck info', 'driver truck', 'equipment', 'devices', 'eld', 'fuel card', 'truck photos'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the My Truck tab.', 'They can see assigned equipment and upload truck photos.'],
  },
  {
    id: 'driver-ica',
    title: 'Driver ICA Signing',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/ica',
    breadcrumb: 'Driver PWA',
    keywords: ['driver ica', 'sign ica', 'independent contractor agreement', 'operator signature', 'ica amendment'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the ICA tab.', 'They review and sign the agreement.', 'Staff can send ICA amendments from the pipeline.'],
  },
  {
    id: 'driver-pay-setup',
    title: 'Driver Pay Setup',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/pay-setup',
    breadcrumb: 'Driver PWA',
    keywords: ['pay setup', 'driver pay', 'payroll', 'settlement', 'contractor pay setup', 'procedures', 'handbook'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Pay Setup tab.', 'They review disclosures and acknowledge BOL, Handbook, and Load Out procedures.'],
  },
  {
    id: 'driver-messages',
    title: 'Driver Messages',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/messages',
    breadcrumb: 'Driver PWA',
    keywords: ['driver messages', 'messages tab', 'driver inbox', 'text driver', 'chat'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Messages tab.', 'They can read and reply to staff messages.'],
  },
  {
    id: 'driver-notifications',
    title: 'Driver Notifications',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/notifications',
    breadcrumb: 'Driver PWA',
    keywords: ['driver notifications', 'alerts', 'driver app alerts', 'view all'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Notifications tab.', 'Tapping View All goes to the Messages inbox.'],
  },
  {
    id: 'driver-resources',
    title: 'Driver Resource Center',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/resources',
    breadcrumb: 'Driver PWA',
    keywords: ['driver resource center', 'driver resources', 'company documents', 'faq', 'help'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Resource Center tab.', 'They can browse FAQs, company documents, and training resources.'],
  },
  {
    id: 'driver-faq',
    title: 'Driver FAQ',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/faq',
    breadcrumb: 'Driver PWA',
    keywords: ['driver faq', 'operator faq', 'owner operator faq', 'help'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the FAQ tab.', 'They can search owner-operator focused help articles.'],
  },
  {
    id: 'driver-forecast',
    title: 'Driver Settlement Forecast',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/forecast',
    breadcrumb: 'Driver PWA',
    keywords: ['settlement forecast', 'forecast', 'driver pay estimate', 'earnings'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the Forecast tab.', 'They see a projected settlement estimate.'],
  },
  {
    id: 'driver-dispatch',
    title: 'Driver Dispatch View',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/dispatch',
    breadcrumb: 'Driver PWA',
    keywords: ['driver dispatch', 'dispatch tab', 'driver status', 'not dispatched', 'dispatched', 'home'],
    audience: DISPATCH_OPS,
    external: true,
    steps: ['Drivers open the Dispatch tab.', 'They can update their status (Dispatched, Home, etc.).'],
  },
  {
    id: 'driver-my-docs',
    title: 'Driver My Documents',
    page: 'Driver PWA',
    surface: 'driver-pwa',
    route: '/operator/my-docs',
    breadcrumb: 'Driver PWA',
    keywords: ['my documents', 'driver my docs', 'personal documents', 'signed documents'],
    audience: ALL_STAFF,
    external: true,
    steps: ['Drivers open the My Docs tab.', 'They see their signed and stored documents.'],
  },

  // Common workflows
  {
    id: 'add-driver',
    title: 'Add a New Driver',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Workflow',
    keywords: ['add driver', 'new driver', 'invite applicant', 'create applicant', 'onboard driver', 'new applicant'],
    audience: ALL_STAFF,
    steps: ['Go to Onboarding Pipeline.', 'Click Add Driver / Invite Applicant.', 'Fill in the driver details and send the invite.', 'The driver receives an email to start the application.'],
  },
  {
    id: 'print-application',
    title: 'Print a Driver Application',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Workflow',
    keywords: ['print application', 'submitted application', 'print', 'pdf', 'driver application'],
    audience: ALL_STAFF,
    steps: ['Open the driver in Onboarding Pipeline.', 'Open the Submitted Application section.', 'Click Print Application.'],
  },
  {
    id: 'send-pei',
    title: 'Send a PEI Request',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Workflow',
    keywords: ['send pei', 'previous employer inquiry', 'email previous employer', 'verification request', 'stage 6'],
    audience: ONBOARDING,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 6 — PE Screening.', 'Add or edit a previous employer.', 'Click Send PEI Request.'],
  },
  {
    id: 'add-previous-employer',
    title: 'Add a Previous Employer',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Workflow',
    keywords: ['add previous employer', 'previous employer', 'employer', 'stage 6', 'pei'],
    audience: ONBOARDING,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 6 — PE Screening.', 'Click Add Previous Employer and fill in the details.'],
  },
  {
    id: 'revert-application',
    title: 'Revert an Application',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Workflow',
    keywords: ['revert', 'revert application', 'revisions', 'send back', 'correction', 'courtesy email'],
    audience: ALL_STAFF,
    steps: ['Open the driver in Onboarding Pipeline.', 'Open the Submitted Application section.', 'Click Revert and choose whether to send a courtesy email.'],
  },
  {
    id: 'propose-changes',
    title: 'Propose Changes to an Application',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Workflow',
    keywords: ['propose changes', 'application corrections', 'edit application', 'changes', 'diff', 'approval'],
    audience: ALL_STAFF,
    steps: ['Open the driver in Onboarding Pipeline.', 'Open the Submitted Application section.', 'Click Propose Changes, edit the fields, and submit.'],
  },
  {
    id: 'email-tracey',
    title: 'Email Tracey McQuilken (DOT Consultant)',
    page: 'Onboarding Pipeline',
    surface: 'management',
    route: '/dashboard?view=pipeline',
    breadcrumb: 'Workflow',
    keywords: ['tracey', 'tracey mcquilken', 'dot consultant', 'email tracey', 'pay setup', 'stage 8', 'documents'],
    audience: ONBOARDING,
    steps: ['Open the driver in Onboarding Pipeline.', 'Expand Stage 8 — Pay Setup.', 'Click Email Tracey McQuilken and attach the documents.'],
  },
  {
    id: 'notify-safety-advisor',
    title: 'Notify Safety Advisor of Deactivation',
    page: 'Driver Hub',
    surface: 'management',
    route: '/dashboard?view=drivers',
    breadcrumb: 'Workflow',
    keywords: ['safety advisor', 'notify safety advisor', 'deactivation', 'tracy', 'marcus', 'dq file', 'compliance records'],
    audience: MANAGEMENT,
    steps: ['Deactivate the driver in Driver Hub.', 'Click Notify Safety Advisor.', 'Review the pre-filled email and click Send Deactivation Notice.'],
  },
  {
    id: 'assign-notification',
    title: 'Assign a Notification to Staff',
    page: 'Notifications',
    surface: 'management',
    route: '/dashboard?view=notifications',
    breadcrumb: 'Workflow',
    keywords: ['assign notification', 'assign', 'delegate', 'notification triage', 'mentions'],
    audience: ALL_STAFF,
    steps: ['Go to Notifications.', 'Open the triage interface.', 'Click Assign and select a staff member.'],
  },
  {
    id: 'birthday-anniversary',
    title: 'Birthday and Anniversary Popups',
    page: 'Overview',
    surface: 'management',
    route: '/dashboard?view=overview',
    breadcrumb: 'Workflow',
    keywords: ['birthday', 'anniversary', 'go live anniversary', 'popup', 'email card', 'celebration'],
    audience: MANAGEMENT,
    steps: ['Birthday and Go Live anniversary popups appear on the Overview.', 'Acknowledge the popup or send a celebratory email card.'],
  },
  {
    id: 'pwa-install',
    title: 'PWA Install Reminders',
    page: 'Overview',
    surface: 'management',
    route: '/dashboard?view=overview',
    breadcrumb: 'Workflow',
    keywords: ['pwa', 'install', 'app install', 'reminder', 'superdrive app', 'download app'],
    audience: MANAGEMENT,
    steps: ['Go to Overview.', 'Review the PWA install stats.', 'Send a reminder to drivers who have not installed the app.'],
  },
  {
    id: 'demo-mode',
    title: 'Demo Mode',
    page: 'Demo Mode',
    surface: 'management',
    route: '/dashboard?view=overview',
    breadcrumb: 'Workflow',
    keywords: ['demo mode', 'sandbox', 'preview', 'test', 'training'],
    audience: MANAGEMENT,
    steps: ['Click Demo Mode in the sidebar or footer.', 'The app enters a sandbox session with UI locks.', 'Exit Demo Mode when finished.'],
  },
];

export const SUGGESTION_POOL: Record<AppRole | 'generic', string[]> = {
  owner: [
    'How do I add a new staff member?',
    'Where do I edit the onboarding pipeline stages?',
    'How do I view fleet compliance?',
    'How do I send a broadcast email?',
    'How do I deactivate a driver?',
    'How do I configure the carrier signature?',
  ],
  management: [
    'How do I approve a driver application?',
    'How do I send a PEI request?',
    'How do I open a driver’s inspection binder from Dispatch?',
    'How do I deactivate a fuel card?',
    'How do I add a new driver?',
    'How do I create an ICA amendment?',
  ],
  onboarding_staff: [
    'How do I send a PEI request?',
    'How do I add a previous employer?',
    'How do I review Stage 5 equipment?',
    'How do I email Tracey McQuilken?',
    'How do I revert an application?',
    'How do I verify the Onboard Systems Assignment Sheet (OSAS)?',
  ],
  dispatcher: [
    'How do I use the Dispatch Board?',
    'How do I view decal photos from Dispatch?',
    'How do I open a driver binder?',
    'How do I download driver dispatch history?',
    'How do I message a driver?',
    'How do I update a driver status?',
  ],
  operator: [
    'How do I upload a document?',
    'How do I sign my ICA?',
    'Where do I see my onboarding progress?',
    'How do I view my messages?',
  ],
  applicant: [
    'How do I complete the application?',
    'Where do I upload my CDL?',
    'How do I check my application status?',
  ],
  truck_owner: [
    'How do I view my truck compliance?',
    'Where do I upload maintenance receipts?',
    'How do I see my truck photos?',
  ],
  generic: [
    'How do I revert an application?',
    'How do I send a PEI request?',
    'How do I add a new driver?',
    'Where do I edit the onboarding pipeline stages?',
    'How do I deactivate a fuel card?',
    'How do I open a driver’s inspection binder from Dispatch?',
  ],
};

export function getSuggestionsForRole(role: AppRole | null): string[] {
  if (!role) return SUGGESTION_POOL.generic;
  return SUGGESTION_POOL[role] ?? SUGGESTION_POOL.generic;
}
