-- Revoke anon EXECUTE on driver_load_pay_estimate. EXPLICITLY FROM anon.
--
-- THE DISTINCTION THIS WHOLE FINDING TURNS ON: `REVOKE ALL ... FROM PUBLIC`
-- does not remove the anon grant. PUBLIC is the implicit pseudo-role; anon is
-- a real named role holding a real ACL entry, placed there at CREATE time by
-- Supabase's default privileges for schema public:
--
--   ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
--     GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;
--
-- The creating migration for this function revoked from PUBLIC and treated the
-- function as locked. It was not. proacl still read anon=X afterwards.
--
-- This function resolves the caller's operator row through
-- public.current_profile_id(); under anon that is null and the function returns
-- the empty estimate, so there was no data leak. The grant is removed anyway:
-- the function's only legitimate caller is a signed-in driver, and an
-- unauthenticated role holding EXECUTE on a definer function that reads
-- pay_policies and load_charges is one body edit away from being one.
--
-- authenticated keeps EXECUTE. service_role keeps EXECUTE.

REVOKE EXECUTE ON FUNCTION public.driver_load_pay_estimate(uuid) FROM anon;
