import { createClient } from 'npm:@supabase/supabase-js@2';
import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';
import { PDFDocument, StandardFonts, rgb } from 'https://esm.sh/pdf-lib@1.17.1';
import { companyIdForUser } from '../_shared/tenancy.ts';
const ROLES=['dispatcher','management','owner'];
const DEFAULT_PACKET=['invoice','bol','pod','rate_confirmation','revised_rate_confirmation','lumper_receipt','scale_ticket','detention_documentation','loadout_pickup_inspection','loadout_delivery_inspection','permit','broker_correspondence','reimbursement_proof','other']; const UUID=/^[0-9a-f-]{36}$/i;
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json'}});
async function cover(loadNumber:string){const p=await PDFDocument.create(),g=p.addPage([612,792]),b=await p.embedFont(StandardFonts.HelveticaBold),r=await p.embedFont(StandardFonts.Helvetica);g.drawRectangle({x:0,y:778,width:612,height:14,color:rgb(.79,.66,.3)});g.drawText('PREVIEW — INVOICE NOT YET ISSUED',{x:48,y:690,size:18,font:b});g.drawText(`Load ${loadNumber}`,{x:48,y:664,size:11,font:r});return new Uint8Array(await p.save());}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders}); if(req.method!=='POST')return json({error:'Method not allowed'},405);
 const auth=req.headers.get('Authorization')??''; if(!auth.startsWith('Bearer '))return json({error:'Unauthorized'},401);
 const url=Deno.env.get('SUPABASE_URL')!,admin=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!),user=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});
 const {data:claims,error:ae}=await user.auth.getClaims(auth.slice(7)),uid=claims?.claims?.sub as string|undefined;if(ae||!uid)return json({error:'Unauthorized'},401);
 const {data:rr}=await admin.from('user_roles').select('role').eq('user_id',uid).in('role',ROLES).limit(1);if(!rr?.length)return json({error:'Forbidden'},403);
 const body=await req.json().catch(()=>({})),loadId=typeof body?.load_id==='string'?body.load_id:'';if(!UUID.test(loadId))return json({error:'Load not found'},404);
 let companyId:string;try{companyId=await companyIdForUser(admin,uid)}catch{return json({error:'Forbidden'},403)}
 const [{data:load},{data:factor}]=await Promise.all([admin.from('loads').select('id,load_number').eq('id',loadId).eq('company_id',companyId).maybeSingle(),admin.from('factoring_companies').select('packet_style').eq('company_id',companyId).eq('is_default',true).maybeSingle()]);
 if(!load)return json({error:'Load not found'},404);if(!factor)return json({error:'No default factoring company is configured'},409);if(factor.packet_style!=='combined')return json({error:'This factoring company uses separate attachments'},409);
 const {data:invoice}=await admin.from('invoices').select('id,invoice_number').eq('load_id',loadId).eq('company_id',companyId).order('created_at',{ascending:false}).limit(1).maybeSingle();let invoiceBytes:Uint8Array;
 if(invoice){const {data:saved}=await admin.from('invoice_files').select('storage_path').eq('invoice_id',invoice.id).eq('company_id',companyId).maybeSingle();if(saved){const {data:blob,error}=await admin.storage.from('invoice-files').download(saved.storage_path);if(error||!blob)return json({error:'The saved invoice PDF could not be read'},500);invoiceBytes=new Uint8Array(await blob.arrayBuffer())}else{const res=await fetch(`${url}/functions/v1/generate-invoice-pdf`,{method:'POST',headers:{Authorization:auth,'Content-Type':'application/json'},body:JSON.stringify({invoice_id:invoice.id,dry_run:true})});if(!res.ok)return json(await res.json().catch(()=>({error:'Invoice preview failed'})),res.status);invoiceBytes=new Uint8Array(await res.arrayBuffer())}}else invoiceBytes=await cover(load.load_number);
 const {data:docs,error:de}=await admin.from('load_documents').select('document_type,document_name,file_path,file_type,uploaded_at').eq('load_id',loadId).eq('company_id',companyId).order('uploaded_at');if(de)return json({error:'Could not read load documents'},500);
 const out=await PDFDocument.create(),manifest:Array<{page:number;document_type:string;source_file:string}>=[];
 const append=async(bytes:Uint8Array,type:string,name:string)=>{let donor;try{donor=await PDFDocument.load(bytes)}catch{throw new Error(`${name} cannot be read as a PDF.`)}for(const page of await out.copyPages(donor,donor.getPageIndices())){out.addPage(page);manifest.push({page:out.getPageCount(),document_type:type,source_file:name})}};
 const include=(factor.packet_includes??{}) as Record<string,boolean>;
 for(const type of factor.packet_order as string[]){if(include[type]===false)continue;if(type==='invoice'){try{await append(invoiceBytes,'invoice',invoice?.invoice_number??'preview invoice')}catch(e){return json({error:e instanceof Error?e.message:String(e)},409)}continue}for(const d of (docs??[]).filter(x=>x.document_type===type)){const name=d.document_name||type;if(!d.file_path)return json({error:`${name} has no stored file.`},409);const {data:blob,error}=await admin.storage.from('load-documents').download(d.file_path);if(error||!blob)return json({error:`${name} could not be read.`},409);const bytes=new Uint8Array(await blob.arrayBuffer()),mime=(d.file_type||blob.type||'').toLowerCase();try{if(mime.includes('pdf')||/\.pdf$/i.test(d.file_path))await append(bytes,type,name);else{const img=mime.includes('png')||/\.png$/i.test(d.file_path)?await out.embedPng(bytes):mime.includes('jpeg')||mime.includes('jpg')||/\.jpe?g$/i.test(d.file_path)?await out.embedJpg(bytes):null;if(!img)return json({error:`${name} has an unsupported file type.`},409);const page=out.addPage([612,792]),scale=Math.min(516/img.width,696/img.height,1);page.drawImage(img,{x:(612-img.width*scale)/2,y:(792-img.height*scale)/2,width:img.width*scale,height:img.height*scale});manifest.push({page:out.getPageCount(),document_type:type,source_file:name})}}catch(e){return json({error:`${name} could not be read: ${e instanceof Error?e.message:String(e)}`},409)}}}
 const bytes=new Uint8Array(await out.save());return new Response(bytes,{headers:{...corsHeaders,'Content-Type':'application/pdf','Content-Disposition':`inline; filename="Packet-${load.load_number}.pdf"`,'X-Page-Count':String(out.getPageCount()),'X-Packet-Bytes':String(bytes.byteLength),'X-Packet-Manifest':encodeURIComponent(JSON.stringify(manifest)),'Access-Control-Expose-Headers':'X-Page-Count, X-Packet-Bytes, X-Packet-Manifest'}})
});
